apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: pdf-chatbot
        metrics_path: /metrics
        scrape_interval: 10s
        static_configs:
          - targets:
              - pdf-chatbot-service.default.svc.cluster.local:8099

      - job_name: prometheus
        metrics_path: /metrics
        static_configs:
          - targets:
              - localhost:9090